
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "decision-layer"
version = "0.1.0"
description = "A lightweight policy evaluation engine for versioned, testable business logic in YAML"
authors = [
  { name="Eevamaija Virtanen" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "pydantic>=1.10",
  "pyyaml",
  "fastapi",
  "uvicorn",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
include = ["decision_layer"]
where = ["."]